version: "3.3"

services:
  ardigital-db:
    restart: on-failure
    image: postgres:10.11-alpine

  ardigital-server:
    restart: on-failure
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    depends_on:
      - ardigital-db
    ports:
      - "8000:8000"

  ardigital-worker:
    restart: on-failure
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python3 backend/manage.py runworkers
    volumes:
      - ./backend:/code
    depends_on:
      - ardigital-db
