version: "3.3"

services:
  ardigital-server:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python3 backend/manage.py runserver
    volumes:
      - .:/backend
    ports:
      - "8000:8000"

  ardigital-worker:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python3 backend/manage.py runworkers
    volumes:
      - .:/backend
