version: "3.3"

x-environment-vars: &environment-vars
  DATABASE_URL: postgres://postgres:postgres@ardigital-db/postgres

services:
  ardigital-db:
    restart: on-failure
    image: postgres:10.11-alpine
    ports:
      - "8200:5432"

  ardigital-server:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    depends_on:
      - ardigital-db
    environment:
      <<: *environment-vars
    ports:
      - "8000:8000"

  ardigital-worker:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python3 backend/manage.py runworkers
    volumes:
      - .:/backend
    depends_on:
      - ardigital-db
    environment:
      <<: *environment-vars
