version: "3.3"

services:
  ardigital-db:
    restart: on-failure
    image: postgres:10.11-alpine

  ardigital-server:
    restart: on-failure
    build: backend
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./backend:/code
    depends_on:
      - ardigital-db
    ports:
      - "80:80"

  ardigital-worker:
    restart: on-failure
    build: backend
    command: python3 manage.py runworkers
    volumes:
      - ./backend:/code

  ardigital-client:
    restart: on-failure
    build: frontend
    ports:
      - "8080:80"
