version: "3.3"

services:
  ardigital-server:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"

  ardigital-worker:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: [ "python3", "-m", "backend.code.worker" ]
    volumes:
      - .:/proj
